version: "3.4"

services:
  nginx:
    image: nginx:1.14.0
    ports:
      - "80:80"
    container_name: mubasir_nginx
    restart: on-failure

  mubasir:
    image: mubasir
    build:
      context: .
      target: application
    container_name: mubasir_app
