version: "3.4"

services:

  mubasir:
    user: ${CONTAINER_UID}:${CONTAINER_GID}
    environment:
      - DJANGO_SETTINGS_MODULE=mubasir.settings.production
    command: gunicorn --config /mubasir/conf/gunicorn.conf.py mubasir.wsgi

  notification_sender:
    user: ${CONTAINER_UID}:${CONTAINER_GID}
    environment:
    - DJANGO_SETTINGS_MODULE=mubasir.settings.production
    command: python manage.py send_notifications
